version: '3.8'

services: 
  nginx:
    build: 
      context: .
      dockerfile: nginx.prod.dockerfile
    ports:
      - 8080:8080
      - 443:443
    depends_on: 
      - mysql
      - php
      - assets
  php:
    build: 
      context: .
      dockerfile: php.prod.dockerfile
  redis:
    image: redis:alpine
  queue-worker:
    build: 
      context: .
      dockerfile: php.prod.dockerfile
    volumes:
      - ./src/:/var/www/html
    depends_on:
      - mysql
      - redis
    command: php /var/www/html/artisan queue:work
  mysql: 
    image: mariadb:10.5
    ports: 
      - 3306:3306 
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes: 
      - ./mysql:/var/lib/mysql
  assets:
    image: node:current-alpine
    volumes: 
      - ./src/:/var/www/html
    command: ["/bin/sh", "-c", "npm install && npm run production"]
    working_dir: /var/www/html
